### ISSUE TITLE
Solution without javascript

### ISSUE THREAD

**Issue by thisisparker** [rentalcustard/guardianpuz#1]
Guardian is refreshingly straightforward with their data! If I'm reading correctly, you can get it with BeautifulSoup with something like:

```python
res = requests.get('https://www.theguardian.com/crosswords/cryptic/27763')
soup = BeautifulSoup(res.text)
d = soup.findAll('div', {'class':'js-crossword'})[0]['data-crossword-data']
```
and then if you have JSON, you can `json.loads` that object and then its entries list has everything you need. Including `group`s, which might be useful for the other question we were looking at!

**Comment by pj-paul** [comment]
Hey @thisisparker I've tried to edit the code as per your suggestion. 

However, I keep hitting an error when using puzpy's `save` function. If you're familiar with puzpy, could you give my code a test run?

**Comment by thisisparker** [comment]
Yep, I hit the same error and was able to track it down. I'm not 100% sure what changed (and I actually think it's possibly an upstream `puzpy` thing between versions) but the fix is on [line 75](https://github.com/pj-paul/guardianpuz/blob/master/guardianpuz.py#L75), by removing the `.encode()` step altogether. It should just read:
```python3
    self.text = text
```

**Comment by pj-paul** [comment]
Great. That fixed it.

**Comment by thisisparker** [comment]
Cool. There _are_ some gotchas around non-ASCII characters and `puzpy` (more properly, the annoying `.puz` format itself), so you may want to do some kind of "normalization" step, but it shouldn't be encoding to `8859-1`, exactly. I have a little crossword scraping script elsewhere that occasionally has to deal with things like accented characters and even HTML, and I normalize with a combination of `html2text` and `unidecode`.

**Comment by pj-paul** [comment]
Could you point me to your normalizing script? I've run into a few encoding issues already. 

eg: Running `python guardianpuz.py -t quick -n 15342` returns the following error: 

> Traceback (most recent call last):
  File "guardianpuz.py", line 102, in <module>
    p.save(save_file_name)
  File "/Users/paulpj/.local/lib/python3.7/site-packages/puz.py", line 225, in save
    puzzle_bytes = self.tobytes()
  File "/Users/paulpj/.local/lib/python3.7/site-packages/puz.py", line 240, in tobytes
    self.global_cksum(), ACROSSDOWN.encode(ENCODING),
  File "/Users/paulpj/.local/lib/python3.7/site-packages/puz.py", line 366, in global_cksum
    cksum = self.text_cksum(cksum)
  File "/Users/paulpj/.local/lib/python3.7/site-packages/puz.py", line 354, in text_cksum
    cksum = data_cksum(clue.encode(ENCODING), cksum)
UnicodeEncodeError: 'latin-1' codec can't encode character '\u2014' in position 16: ordinal not in range(256)

**Comment by thisisparker** [comment]
Sure, although probably your best move is to use `unidecode` or something similar. Another dependency but [it's easy and works](https://pypi.org/project/Unidecode/). The character it's choking on is an em dash (`—`) which is probably pretty common and I think will be normalized into `--` by `unidecode` out of the box. I'd just put it in line 75 there, so `self.text = unidecode(text)`, or however the syntax works.

**Comment by mixographer** [comment]
Thanks for this @pj-paul and @thisisparker . I noticed @rentalcustard never took the pull request. The current version works, but it still chokes on some characters. I tried to mess with unidecoding, but didn't have any luck. here is an example that fails: https://www.theguardian.com/crosswords/everyman/3970 it does have two or three cases of en-dash or em-dash in the clue set.

**Comment by mixographer** [comment]
oh. Disregard my last comment. I see that everyman must be a prize crossword and the solution isn't in the .js until some time later. Doh! Thanks!
